name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 15 * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - run: git clone https://github.com/ppy/osu.git
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./osu
    - name: Build
      run: dotnet build -c Release --no-restore --output out/
      working-directory: ./osu/osu.Desktop
    - run: mkdir $GITHUB_WORKSPACE/upload
    - name: Copy all rulesets to upload folder
      run: find . -name "osu.Game.Rulesets.*.dll" -print -exec mv {} $GITHUB_WORKSPACE/upload \; 
      working-directory: ./osu/osu.Desktop/out/
      
    - name: Adding hash.txt file
      run: bash $GITHUB_WORKSPACE/hash.sh
      working-directory: upload
    - name: zip files
      run: zip -0 -j rulesets.zip $GITHUB_WORKSPACE/upload/*
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: rulesets.zip
        name: dlls
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Build ${{ github.GITHUB_RUN_ID }}" 
          files: |
            rulesets.zip
    
