name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: git clone https://github.com/ppy/osu.git
    - run: cd osu
    - run: pwd && ls 
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output out/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: out
    
